name: Feature request
description: An idea or a new game source
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What you would like
    validations:
      required: true
